insert into actors (actor_id, name, agency, active_since, location) values (1, 'Bern', 'Mills, Okuneva and Kuphal', 1992, 'Pennsylvania');
insert into actors (actor_id, name, agency, active_since, location) values (2, 'Andria', 'Farrell-Jacobi', 2001, 'Georgia');
insert into actors (actor_id, name, agency, active_since, location) values (3, 'Marysa', 'Fahey, Purdy and Fay', 2003, 'Louisiana');
insert into actors (actor_id, name, agency, active_since, location) values (4, 'Nikolaus', 'Larson-Jerde', 2013, 'Pennsylvania');
insert into actors (actor_id, name, agency, active_since, location) values (5, 'Hildegaard', 'Borer-Rodriguez', 2010, 'Kentucky');
insert into actors (actor_id, name, agency, active_since, location) values (6, 'Orlan', 'Price-Ratke', 1995, 'Texas');
insert into actors (actor_id, name, agency, active_since, location) values (7, 'Camala', 'Effertz, Murray and McDermott', 2009, 'Florida');
insert into actors (actor_id, name, agency, active_since, location) values (8, 'Truda', 'Swift, Nicolas and Schoen', 1999, 'California');
insert into actors (actor_id, name, agency, active_since, location) values (9, 'Nicholle', 'Weissnat-Greenholt', 2013, 'Connecticut');
insert into actors (actor_id, name, agency, active_since, location) values (10, 'Adi', 'Pacocha, Walsh and Kassulke', 2010, 'Tennessee');
insert into actors (actor_id, name, agency, active_since, location) values (11, 'Kristos', 'Labadie LLC', 2002, 'California');
insert into actors (actor_id, name, agency, active_since, location) values (12, 'Tiena', 'Auer-Rolfson', 2001, 'North Carolina');
insert into actors (actor_id, name, agency, active_since, location) values (13, 'Washington', 'Shields, Hermiston and Grant', 1995, 'Colorado');
insert into actors (actor_id, name, agency, active_since, location) values (14, 'Marco', 'Dach, McDermott and Goyette', 2006, 'Michigan');
insert into actors (actor_id, name, agency, active_since, location) values (15, 'Jethro', 'Hauck, Walsh and Upton', 1997, 'Texas');
insert into actors (actor_id, name, agency, active_since, location) values (16, 'Desiree', 'Steuber Inc', 2004, 'California');
insert into actors (actor_id, name, agency, active_since, location) values (17, 'Leonardo di Caprio', 'Bruen, Medhurst and Doyle', 2004, 'South Carolina');
insert into actors (actor_id, name, agency, active_since, location) values (18, 'Rockie', 'Jacobson-Paucek', 1987, 'Florida');
insert into actors (actor_id, name, agency, active_since, location) values (19, 'Malachi', 'Mohr-Johnson', 2008, 'Missouri');
insert into actors (actor_id, name, agency, active_since, location) values (20, 'Oliver', 'Hammes Group', 2007, 'Maryland');
